version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 98532414
      POSTGRES_DB: backend.uni
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: mongodatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - postgres
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend.uni
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 98532414
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mongo.backend.uni
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  mongo_data:
